In [1]:
import es_distributed.tf_util as U
import tensorflow as tf

from es_distributed.policies import catcher, CatchPolicy
from es_distributed.es import *
from es_distributed import policies


exp = {
  "config": {
    "calc_obstat_prob": 0.0,
    "episodes_per_batch": 10000,
    "eval_prob": 0.03,
    "l2coeff": 0.005,
    "noise_stdev": 0.02,
    "snapshot_freq": 5,
    "timesteps_per_batch": 100000,
    "return_proc_mode": "centered_rank",
    "episode_cutoff_mode": "env_default"
  },
  "env_id": "catcher",
  "exp_prefix": "humanoid",
  "optimizer": {
    "args": {
      "stepsize": 0.01
    },
    "type": "adam"
  },
  "policy": {
    "args": {
      "connection_type": "ff",
      "hidden_dims": [
        100,
        100
      ],
      "nonlin_type": "tanh"
    },
    "type": "CatchPolicy"
  }
}


config, env, sess, policy = setup(exp, single_threaded=False)
policy.initialize_from('/home/aignatov/snapshot.h5')
policy.rollout(env)

Instructions for updating:
Please use tf.global_variables instead.
Instructions for updating:
Use `tf.variables_initializer` instead.


(array([    0.,     0.,     0.,     0.,     0.,     0.,     0.,  1500.], dtype=float32),
 8)

In [2]:
for i in range(100):
    print(policy.rollout(env)[0][-1])

1500.0
1500.0
1500.0
-1000.0
-1000.0
-1000.0
1000.0
-1000.0
1500.0
1500.0
-1000.0
1500.0
1500.0
1500.0
-1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
-1000.0
-1000.0
1500.0
-1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
-1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
-1000.0
1500.0
1500.0
1500.0
1500.0
1500.0
1000.0
1500.0
1500.0
1500.0
-1000.0


In [3]:
init = tf.initialize_all_variables()
sess.run(init)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [4]:
nextQ = tf.placeholder(shape=policy.a.shape,dtype=tf.float32)
loss = tf.reduce_mean(tf.square(nextQ - policy.a))
#trainer = tf.train.RMSPropOptimizer(0.001, momentum=0.95, epsilon=0.01)
trainer = tf.train.AdamOptimizer(learning_rate=0.01)
updateModel = trainer.minimize(loss)


import json
import numpy as np

class Catch(object):
    def __init__(self, grid_size=10):
        self.grid_size = grid_size
        self.reset()

    def _update_state(self, action):
        """
        Input: action and states
        Ouput: new states and reward
        """
        state = self.state
        if action == 0:  # left
            action = -1
        elif action == 1:  # stay
            action = 0
        else:
            action = 1  # right
        f0, f1, basket = state[0]
        new_basket = min(max(1, basket + action), self.grid_size-1)
        f0 += 1
        out = np.asarray([f0, f1, new_basket])
        out = out[np.newaxis]

        assert len(out.shape) == 2
        self.state = out

    def _draw_state(self):
        im_size = (self.grid_size,)*2
        state = self.state[0]
        canvas = np.zeros(im_size)
        canvas[state[0], state[1]] = 1  # draw fruit
        canvas[-1, state[2]-1:state[2] + 2] = 1  # draw basket
        return canvas

    def _get_reward(self):
        fruit_row, fruit_col, basket = self.state[0]
        if fruit_row == self.grid_size-1:
            if abs(fruit_col - basket) <= 1:
                return 1000
            else:
                return -1000
        else:
            return 0

    def _is_over(self):
        if self.state[0, 0] == self.grid_size-1:
            return True
        else:
            return False

    def observe(self):
        canvas = self._draw_state()
        return canvas.reshape((1, -1))

    def act(self, action):
        self._update_state(action)
        reward = self._get_reward()
        game_over = self._is_over()
        return self.observe(), reward, game_over

    def reset(self):
        n = np.random.randint(0, self.grid_size-1, size=1)
        m = np.random.randint(1, self.grid_size-2, size=1)
        self.state = np.asarray([0, n, m])[np.newaxis]


class ExperienceReplay(object):
    def __init__(self, max_memory=100, discount=.9):
        self.max_memory = max_memory
        self.memory = list()
        self.discount = discount

    def remember(self, states, game_over):
        # memory[i] = [[state_t, action_t, reward_t, state_t+1], game_over?]
        self.memory.append([states, game_over])
        if len(self.memory) > self.max_memory:
            del self.memory[0]

    def get_batch(self, policy, batch_size=10):
        len_memory = len(self.memory)
        num_actions = int(policy.a.shape[-1])
        env_dim = self.memory[0][0][0].shape[1]
        inputs = np.zeros((min(len_memory, batch_size), env_dim))
        targets = np.zeros((inputs.shape[0], num_actions))
        for i, idx in enumerate(np.random.randint(0, len_memory,
                                                  size=inputs.shape[0])):
            state_t, action_t, reward_t, state_tp1 = self.memory[idx][0]
            game_over = self.memory[idx][1]

            inputs[i:i+1] = state_t
            # There should be no target values for actions not taken.
            # Thou shalt not correct actions not taken #deep
            targets[i] = policy.act(state_t)[0]
            Q_sa = np.max(policy.act(state_tp1)[0])
            if game_over:  # if game_over is True
                targets[i, action_t] = reward_t
            else:
                # reward_t + gamma * max_a' Q(s', a')
                targets[i, action_t] = reward_t + self.discount * Q_sa
        return inputs, targets


epsilon = .1  # exploration
num_actions = 3  # [move_left, stay, move_right]
epoch = 100000
max_memory = 500
hidden_size = 100
batch_size = 1
grid_size = 10

#model = Sequential()
#model.add(Dense(hidden_size, input_shape=(grid_size**2,), activation='relu'))
#model.add(Dense(hidden_size, activation='relu'))
#model.add(Dense(num_actions))
#model.compile(sgd(lr=.2), "mse")

# If you want to continue training from a previous model, just uncomment the line bellow
# model.load_weights("model.h5")

# Define environment/game
env = Catch(grid_size)

# Initialize experience replay object
exp_replay = ExperienceReplay(max_memory=max_memory)

# Train
win_cnt = 0
for e in range(epoch):
    loss = 0.
    env.reset()
    game_over = False
    # get initial input
    input_t = env.observe()

    while not game_over:
        input_tm1 = input_t
        # get next action
        if np.random.rand() <= epsilon:
            action = np.random.randint(0, num_actions, size=1)
        else:
            q = policy.act(input_tm1)
            action = np.argmax(q[0])

        # apply action, get rewards and new state
        input_t, reward, game_over = env.act(action)
        if reward > 0:
            win_cnt += 1

        # store experience
        exp_replay.remember([input_tm1, action, reward, input_t], game_over)

    # adapt model
    inputs, targets = exp_replay.get_batch(policy, batch_size=batch_size)

    print(policy.act([catcher().reset()])[0])
    #loss += model.train_on_batch(inputs, targets)[0]
    U.eval(updateModel, {policy.o:inputs,nextQ:targets})
    print(policy.act([catcher().reset()])[0])
    print('\n')

    print("Epoch {:03d}/999 | Win count {}".format(e, win_cnt))



[ 0.0014195  -0.00406937  0.00154286]


FailedPreconditionError: Attempting to use uninitialized value beta2_power
	 [[Node: beta2_power/read = Identity[T=DT_FLOAT, _class=["loc:@CatchPolicy/l0/b"], _device="/job:localhost/replica:0/task:0/cpu:0"](beta2_power)]]

Caused by op 'beta2_power/read', defined at:
  File "/home/aignatov/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/aignatov/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-d3e23bbaf82b>", line 5, in <module>
    updateModel = trainer.minimize(loss)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 325, in minimize
    name=name)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 446, in apply_gradients
    self._create_slots([_get_variable_for(v) for v in var_list])
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/training/adam.py", line 129, in _create_slots
    trainable=False)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1679, in variable
    caching_device=caching_device, name=name, dtype=dtype)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 199, in __init__
    expected_shape=expected_shape)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 330, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1400, in identity
    result = _op_def_lib.apply_op("Identity", input=input, name=name)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aignatov/miniconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value beta2_power
	 [[Node: beta2_power/read = Identity[T=DT_FLOAT, _class=["loc:@CatchPolicy/l0/b"], _device="/job:localhost/replica:0/task:0/cpu:0"](beta2_power)]]


In [4]:
policy.a.shape

TensorShape([Dimension(None), Dimension(3)])

In [5]:
env = catcher()
for i in range(100):
    print(policy.rollout(env)[0][-1])

-1000.0
1000.0
-1000.0
1500.0
-1000.0
1000.0
1500.0
-1000.0
-1000.0
1000.0
-1000.0
1000.0
-1000.0
-1000.0
-1000.0
-1000.0
1000.0
-1000.0
-1000.0
1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
1500.0
-1000.0
1000.0
-1000.0
-1000.0
-1000.0
1500.0
1000.0
-1000.0
1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
1000.0
-1000.0
1000.0
1000.0
-1000.0
-1000.0
-1000.0
1500.0
1000.0
-1000.0
-1000.0
1500.0
-1000.0
-1000.0
-1000.0
1000.0
-1000.0
-1000.0
-1000.0
-1000.0
1500.0
-1000.0
-1000.0
1000.0
-1000.0
-1000.0
1500.0
-1000.0
1000.0
1000.0
1500.0
-1000.0
-1000.0
-1000.0
1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
-1000.0
1000.0
-1000.0
1500.0
-1000.0


# standard Qlearn

In [12]:
import json
import numpy as np
from keras.models import Sequential
from keras.layers.core import Dense
from keras.optimizers import sgd


class Catch(object):
    def __init__(self, grid_size=10):
        self.grid_size = grid_size
        self.reset()

    def _update_state(self, action):
        """
        Input: action and states
        Ouput: new states and reward
        """
        state = self.state
        if action == 0:  # left
            action = -1
        elif action == 1:  # stay
            action = 0
        else:
            action = 1  # right
        f0, f1, basket = state[0]
        new_basket = min(max(1, basket + action), self.grid_size-1)
        f0 += 1
        out = np.asarray([f0, f1, new_basket])
        out = out[np.newaxis]

        assert len(out.shape) == 2
        self.state = out

    def _draw_state(self):
        im_size = (self.grid_size,)*2
        state = self.state[0]
        canvas = np.zeros(im_size)
        canvas[state[0], state[1]] = 1  # draw fruit
        canvas[-1, state[2]-1:state[2] + 2] = 1  # draw basket
        return canvas

    def _get_reward(self):
        fruit_row, fruit_col, basket = self.state[0]
        if fruit_row == self.grid_size-1:
            if abs(fruit_col - basket) <= 1:
                return 1000
            else:
                return -1000
        else:
            return 0

    def _is_over(self):
        if self.state[0, 0] == self.grid_size-1:
            return True
        else:
            return False

    def observe(self):
        canvas = self._draw_state()
        return canvas.reshape((1, -1))

    def act(self, action):
        self._update_state(action)
        reward = self._get_reward()
        game_over = self._is_over()
        return self.observe(), reward, game_over

    def reset(self):
        n = np.random.randint(0, self.grid_size-1, size=1)
        m = np.random.randint(1, self.grid_size-2, size=1)
        self.state = np.asarray([0, n, m])[np.newaxis]


class ExperienceReplay(object):
    def __init__(self, max_memory=100, discount=.9):
        self.max_memory = max_memory
        self.memory = list()
        self.discount = discount

    def remember(self, states, game_over):
        # memory[i] = [[state_t, action_t, reward_t, state_t+1], game_over?]
        self.memory.append([states, game_over])
        if len(self.memory) > self.max_memory:
            del self.memory[0]

    def get_batch(self, model, batch_size=10):
        len_memory = len(self.memory)
        num_actions = model.output_shape[-1]
        env_dim = self.memory[0][0][0].shape[1]
        inputs = np.zeros((min(len_memory, batch_size), env_dim))
        targets = np.zeros((inputs.shape[0], num_actions))
        for i, idx in enumerate(np.random.randint(0, len_memory,
                                                  size=inputs.shape[0])):
            state_t, action_t, reward_t, state_tp1 = self.memory[idx][0]
            game_over = self.memory[idx][1]

            inputs[i:i+1] = state_t
            # There should be no target values for actions not taken.
            # Thou shalt not correct actions not taken #deep
            targets[i] = model.predict(state_t)[0]
            Q_sa = np.max(model.predict(state_tp1)[0])
            if game_over:  # if game_over is True
                targets[i, action_t] = reward_t
            else:
                # reward_t + gamma * max_a' Q(s', a')
                targets[i, action_t] = reward_t + self.discount * Q_sa
        return inputs, targets


if __name__ == "__main__":
    # parameters
    epsilon = .1  # exploration
    num_actions = 3  # [move_left, stay, move_right]
    epoch = 50000
    max_memory = 500
    hidden_size = 100
    batch_size = 50
    grid_size = 10

    model = Sequential()
    model.add(Dense(hidden_size, input_shape=(grid_size**2,), activation='relu'))
    model.add(Dense(hidden_size, activation='relu'))
    model.add(Dense(num_actions))
    model.compile(sgd(lr=.2), "mse")

    # If you want to continue training from a previous model, just uncomment the line bellow
    # model.load_weights("model.h5")

    # Define environment/game
    env = Catch(grid_size)

    # Initialize experience replay object
    exp_replay = ExperienceReplay(max_memory=max_memory)

    # Train
    win_cnt = 0
    for e in range(epoch):
        loss = 0.
        env.reset()
        game_over = False
        # get initial input
        input_t = env.observe()

        while not game_over:
            input_tm1 = input_t
            # get next action
            if np.random.rand() <= epsilon:
                action = np.random.randint(0, num_actions, size=1)
            else:
                q = model.predict(input_tm1)
                action = np.argmax(q[0])

            # apply action, get rewards and new state
            input_t, reward, game_over = env.act(action)
            if reward == 1:
                win_cnt += 1
        
        
        # store experience
        exp_replay.remember([input_tm1, action, reward, input_t], game_over)

        # adapt model
        
   
        inputs, targets = exp_replay.get_batch(model, batch_size=batch_size)

        loss += model.train_on_batch(inputs, targets)
        if not e % 20:
            print(model.predict(input_t)[0])
            print("Epoch {:03d}/999 | Loss {:.4f} | Win count {}".format(e, loss, win_cnt))
            print('\n')


[-0.52314901  0.26815662 -0.11703966]
Epoch 000/999 | Loss 0.3931 | Win count 0


[-0.76496881 -0.29357025 -0.45738214]
Epoch 020/999 | Loss 0.0820 | Win count 6


[-0.55678451 -0.78584528  0.01110704]
Epoch 040/999 | Loss 0.1306 | Win count 15


[-0.70658523 -0.4111976  -0.26637673]
Epoch 060/999 | Loss 0.1297 | Win count 21


[-0.61078697 -0.15010278 -0.38725239]
Epoch 080/999 | Loss 0.0669 | Win count 27


[-0.24727343 -1.66710675 -0.84826964]
Epoch 100/999 | Loss 0.0653 | Win count 35


[-0.27554655 -1.07338965 -0.50764942]
Epoch 120/999 | Loss 0.0662 | Win count 41


[-0.5364942  -0.82563227 -0.50051981]
Epoch 140/999 | Loss 0.0668 | Win count 45


[-0.54219073 -0.81450105 -0.37299335]
Epoch 160/999 | Loss 0.0435 | Win count 53


[-0.80052102 -0.3699109  -0.58216071]
Epoch 180/999 | Loss 0.0538 | Win count 60


[-0.66462022 -1.05748928 -0.91957682]
Epoch 200/999 | Loss 0.0371 | Win count 67


[-0.53815812 -0.88478017 -0.65387791]
Epoch 220/999 | Loss 0.0255 | Win count 73


[-0.76

[-0.14288101 -0.29163629 -0.45404333]
Epoch 1960/999 | Loss 0.0005 | Win count 817


[-0.43067124 -1.09726095 -1.08771956]
Epoch 1980/999 | Loss 0.0021 | Win count 824


[ 0.08923449  0.02105755 -0.20762676]
Epoch 2000/999 | Loss 0.0022 | Win count 830


[-0.10822859 -0.25284892 -0.20577809]
Epoch 2020/999 | Loss 0.0075 | Win count 844


[-0.49375916 -0.42131934 -0.10741401]
Epoch 2040/999 | Loss 0.0016 | Win count 853


[ 0.03586473  0.05885044  0.21807949]
Epoch 2060/999 | Loss 0.0067 | Win count 858


[-0.43251523 -1.13688028 -1.05983198]
Epoch 2080/999 | Loss 0.0064 | Win count 866


[-0.21068676 -0.05694053 -0.07424739]
Epoch 2100/999 | Loss 0.0032 | Win count 873


[-0.60829121 -0.83340412 -0.55772769]
Epoch 2120/999 | Loss 0.0039 | Win count 881


[-0.38627851 -0.66381812 -0.68824548]
Epoch 2140/999 | Loss 0.0008 | Win count 888


[-0.44551072  0.05389842  0.03703694]
Epoch 2160/999 | Loss 0.0019 | Win count 898


[ 0.38833565 -0.36508662  0.04524489]
Epoch 2180/999 | Loss 0.000

[-0.28609657 -0.52822584 -0.32029372]
Epoch 3880/999 | Loss 0.0008 | Win count 1552


[-0.15332368 -0.38924983 -0.41888767]
Epoch 3900/999 | Loss 0.0006 | Win count 1561


[ 0.65098625 -0.3413482   0.17474589]
Epoch 3920/999 | Loss 0.0012 | Win count 1572


[-0.95370728 -0.95205092 -0.19278575]
Epoch 3940/999 | Loss 0.0014 | Win count 1579


[-0.65081352 -0.68368655 -0.77859116]
Epoch 3960/999 | Loss 0.0013 | Win count 1585


[ 0.70152736  0.23473878  0.87368244]
Epoch 3980/999 | Loss 0.0015 | Win count 1594


[-0.57012677 -0.51029646 -0.81152433]
Epoch 4000/999 | Loss 0.0233 | Win count 1604


[-0.52650589 -0.03576432 -0.36003491]
Epoch 4020/999 | Loss 0.0005 | Win count 1609


[-0.92457402 -0.62212759 -0.19091761]
Epoch 4040/999 | Loss 0.0041 | Win count 1614


[-0.61142355 -0.52274716 -0.11451997]
Epoch 4060/999 | Loss 0.0022 | Win count 1618


[-0.49152148 -0.52056527 -0.73942935]
Epoch 4080/999 | Loss 0.0007 | Win count 1621


[ 0.01832208  0.06825092  0.32943821]
Epoch 4100/999 |

[ 0.04305717 -0.08667633 -0.0689635 ]
Epoch 5800/999 | Loss 0.0005 | Win count 2290


[-0.45669466 -0.75853395 -0.57592499]
Epoch 5820/999 | Loss 0.0001 | Win count 2297


[-0.26857543 -0.66001326 -0.446747  ]
Epoch 5840/999 | Loss 0.0004 | Win count 2305


[ 0.01829518 -0.14205329  0.12431978]
Epoch 5860/999 | Loss 0.0005 | Win count 2313


[-0.15182362 -0.35019845 -0.43173003]
Epoch 5880/999 | Loss 0.0001 | Win count 2322


[ 0.00880757 -0.15338011 -0.27448022]
Epoch 5900/999 | Loss 0.0001 | Win count 2333


[-0.2883856  -0.19969983 -0.64050108]
Epoch 5920/999 | Loss 0.0013 | Win count 2339


[-0.31668037 -0.66904932 -0.39588097]
Epoch 5940/999 | Loss 0.0007 | Win count 2347


[-0.2609756  -0.7307781  -0.53677952]
Epoch 5960/999 | Loss 0.0003 | Win count 2357


[-0.44742504 -0.28048274 -0.65242553]
Epoch 5980/999 | Loss 0.0011 | Win count 2363


[ 0.69151533 -0.55463809 -0.0327882 ]
Epoch 6000/999 | Loss 0.0008 | Win count 2373


[-0.30124485 -0.70142043 -0.4320758 ]
Epoch 6020/999 |

[-0.19916669 -0.22187331 -0.14875278]
Epoch 7720/999 | Loss 0.0048 | Win count 3128


[-0.0735445  -0.17045543 -0.30985498]
Epoch 7740/999 | Loss 0.0029 | Win count 3135


[-0.74919128 -0.25581583 -0.37056443]
Epoch 7760/999 | Loss 0.0009 | Win count 3142


[-0.08417642 -0.14658906 -0.52696854]
Epoch 7780/999 | Loss 0.0006 | Win count 3150


[ 0.66297531 -0.34041578 -0.32316485]
Epoch 7800/999 | Loss 0.0001 | Win count 3160


[-0.02165966 -0.40152413 -0.98865712]
Epoch 7820/999 | Loss 0.0054 | Win count 3171


[-0.01201412 -0.04095753 -0.20733871]
Epoch 7840/999 | Loss 0.0001 | Win count 3177


[ 0.06276543 -0.62166601 -0.64452654]
Epoch 7860/999 | Loss 0.0001 | Win count 3187


[ 0.06673294 -0.42963561 -0.37760124]
Epoch 7880/999 | Loss 0.0002 | Win count 3194


[-0.32722509 -0.23688811 -0.16213857]
Epoch 7900/999 | Loss 0.0002 | Win count 3202


[-0.31845099 -0.753227   -0.19569124]
Epoch 7920/999 | Loss 0.0001 | Win count 3206


[  9.59664583e-04  -7.88950980e-01  -9.96344030e-01]
E

[-0.14358518 -0.29657906 -0.21437903]
Epoch 9640/999 | Loss 0.0001 | Win count 3966


[ 0.15000188 -0.30383453 -0.52663547]
Epoch 9660/999 | Loss 0.0011 | Win count 3969


[ 0.01724708 -0.33215311  0.09548687]
Epoch 9680/999 | Loss 0.0000 | Win count 3977


[-0.11895014  0.18253726 -0.14515011]
Epoch 9700/999 | Loss 0.0001 | Win count 3985


[ 0.1618689  -0.30561402 -0.51731598]
Epoch 9720/999 | Loss 0.0007 | Win count 3994


[-0.15344606 -0.31738687 -0.23108006]
Epoch 9740/999 | Loss 0.0000 | Win count 4001


[-0.25871426 -0.46140665 -0.8045063 ]
Epoch 9760/999 | Loss 0.0002 | Win count 4012


[-0.30551147 -0.03130642 -0.44266847]
Epoch 9780/999 | Loss 0.0000 | Win count 4023


[-0.09991323 -0.52989733 -0.74679261]
Epoch 9800/999 | Loss 0.0000 | Win count 4035


[ 0.08479737 -0.2990095  -0.42054802]
Epoch 9820/999 | Loss 0.0001 | Win count 4043


[ 0.23878771 -0.3025223   0.05365125]
Epoch 9840/999 | Loss 0.0000 | Win count 4051


[-0.04786536 -0.29440275 -0.32408226]
Epoch 9860/999 |

[-0.28016385 -0.42437026 -0.80778915]
Epoch 11540/999 | Loss 0.0001 | Win count 4745


[ 0.24714343 -0.14177738 -0.31638336]
Epoch 11560/999 | Loss 0.0002 | Win count 4755


[-0.14666067 -0.21398568 -0.34748617]
Epoch 11580/999 | Loss 0.0003 | Win count 4765


[ 0.18714309 -0.28483564 -0.08259926]
Epoch 11600/999 | Loss 0.0013 | Win count 4771


[-0.05280282 -0.16176793 -0.32943335]
Epoch 11620/999 | Loss 0.0002 | Win count 4780


[-0.17085952 -0.62108397 -0.26583803]
Epoch 11640/999 | Loss 0.0000 | Win count 4788


[-0.37088722 -0.35722047 -0.91445512]
Epoch 11660/999 | Loss 0.0001 | Win count 4796


[ 0.17961489 -0.32934645 -0.04892515]
Epoch 11680/999 | Loss 0.0007 | Win count 4806


[ 0.74468523 -0.35219857  0.09150016]
Epoch 11700/999 | Loss 0.0001 | Win count 4812


[ 0.72165328 -0.23269957 -0.09500728]
Epoch 11720/999 | Loss 0.0007 | Win count 4824


[-0.30240142 -0.23420072 -0.12073031]
Epoch 11740/999 | Loss 0.0001 | Win count 4831


[-0.33039635 -0.40619379 -0.80366874]
Epoch

[ 0.16809002 -0.25230956 -0.39590988]
Epoch 13440/999 | Loss 0.0000 | Win count 5561


[ 0.22176252 -0.26886129 -0.40136442]
Epoch 13460/999 | Loss 0.0004 | Win count 5568


[-0.16038989 -0.72752732  0.19891742]
Epoch 13480/999 | Loss 0.0000 | Win count 5577


[-0.01969346 -0.34556651 -0.05743507]
Epoch 13500/999 | Loss 0.0000 | Win count 5585


[ 0.07062904 -0.38451624 -0.50449419]
Epoch 13520/999 | Loss 0.0000 | Win count 5592


[-0.20778579 -0.26577255 -0.36037096]
Epoch 13540/999 | Loss 0.0000 | Win count 5601


[-0.20678931 -0.15778875 -0.43633944]
Epoch 13560/999 | Loss 0.0000 | Win count 5606


[-0.21229717 -0.25891885 -0.33923766]
Epoch 13580/999 | Loss 0.0000 | Win count 5612


[ 0.64337236 -0.18806347 -0.10856538]
Epoch 13600/999 | Loss 0.0000 | Win count 5616


[-0.65478969 -0.48371917 -1.12241113]
Epoch 13620/999 | Loss 0.0001 | Win count 5624


[-0.21039756 -0.25544077 -0.32802224]
Epoch 13640/999 | Loss 0.0001 | Win count 5632


[ 0.19429263  0.04325156  0.26652434]
Epoch

[ 0.21567602 -0.38591141 -0.03482788]
Epoch 15320/999 | Loss 0.0019 | Win count 6334


[-0.06987495 -0.22275054 -0.33104241]
Epoch 15340/999 | Loss 0.0001 | Win count 6345


[-0.20332009 -0.20932806 -0.54929203]
Epoch 15360/999 | Loss 0.0004 | Win count 6351


[ 0.12221016 -0.18677156 -0.44946915]
Epoch 15380/999 | Loss 0.0001 | Win count 6362


[-0.15936972 -0.44731522 -0.25617766]
Epoch 15400/999 | Loss 0.0001 | Win count 6375


[-0.35132006  0.0528389  -0.26652718]
Epoch 15420/999 | Loss 0.0007 | Win count 6383


[-0.17807022 -0.20696694 -0.53177941]
Epoch 15440/999 | Loss 0.0000 | Win count 6392


[-0.16858925 -0.45716226 -0.27098536]
Epoch 15460/999 | Loss 0.0000 | Win count 6401


[-0.16232064 -0.19324674 -0.53995794]
Epoch 15480/999 | Loss 0.0002 | Win count 6409


[ 0.00091437 -0.45580959 -0.02680478]
Epoch 15500/999 | Loss 0.0005 | Win count 6420


[-0.05546274 -0.4426648  -0.16870497]
Epoch 15520/999 | Loss 0.0001 | Win count 6430


[-0.2845473  -0.42605728 -1.12799954]
Epoch

[ 0.59972155 -0.15608169 -0.19469911]
Epoch 17220/999 | Loss 0.0000 | Win count 7072


[-0.0909151  -0.28105566 -0.36746135]
Epoch 17240/999 | Loss 0.0000 | Win count 7084


[ -2.93295950e-01  -3.91893834e-02  -2.56089494e-04]
Epoch 17260/999 | Loss 0.0000 | Win count 7090


[ 0.40037534 -0.0296392   0.14840195]
Epoch 17280/999 | Loss 0.0002 | Win count 7099


[-0.08931205 -0.27831778 -0.36039278]
Epoch 17300/999 | Loss 0.0001 | Win count 7107


[-0.08782652 -0.27382112 -0.35749301]
Epoch 17320/999 | Loss 0.0000 | Win count 7115


[-0.08757167 -0.27341628 -0.35761243]
Epoch 17340/999 | Loss 0.0001 | Win count 7125


[ 0.02409782  0.15053041 -0.1437062 ]
Epoch 17360/999 | Loss 0.0000 | Win count 7131


[-0.19126618 -0.47176424 -0.3067953 ]
Epoch 17380/999 | Loss 0.0000 | Win count 7143


[ 0.58147717 -0.16835162 -0.1935623 ]
Epoch 17400/999 | Loss 0.0000 | Win count 7148


[-0.14786033 -1.05962002 -1.00698805]
Epoch 17420/999 | Loss 0.0000 | Win count 7153


[-0.134863   -0.4009085  -0.

[-0.15114853 -0.09847319 -0.44072837]
Epoch 19100/999 | Loss 0.0001 | Win count 7762


[-0.31914553 -0.89072973 -0.30849463]
Epoch 19120/999 | Loss 0.0024 | Win count 7771


[-0.16759332 -0.10898124 -0.42894456]
Epoch 19140/999 | Loss 0.0001 | Win count 7778


[ 0.12677145 -0.1825763  -0.10383298]
Epoch 19160/999 | Loss 0.0000 | Win count 7787


[-0.37205568 -0.12216694 -0.66070694]
Epoch 19180/999 | Loss 0.0000 | Win count 7795


[-0.0702889  -0.5618484  -0.25101516]
Epoch 19200/999 | Loss 0.0000 | Win count 7804


[ 0.07018472 -0.29975215  0.04698187]
Epoch 19220/999 | Loss 0.0001 | Win count 7810


[-0.25537351 -0.12330203 -0.58354008]
Epoch 19240/999 | Loss 0.0000 | Win count 7819


[-0.29908627 -0.37101859 -0.8507638 ]
Epoch 19260/999 | Loss 0.0000 | Win count 7826


[-0.35681355 -0.38644123 -0.79738569]
Epoch 19280/999 | Loss 0.0001 | Win count 7831


[-0.70618588 -0.44973525 -0.44010657]
Epoch 19300/999 | Loss 0.0000 | Win count 7839


[-0.70081669 -0.58995688 -0.92499042]
Epoch

[ 0.2199932   0.03065774  0.06462274]
Epoch 21000/999 | Loss 0.0000 | Win count 8503


[-0.51082838 -0.15423587 -0.26681694]
Epoch 21020/999 | Loss 0.0000 | Win count 8511


[-0.36212954 -0.49092668 -0.78604901]
Epoch 21040/999 | Loss 0.0000 | Win count 8518


[ 0.19952501 -0.21241233 -0.49821764]
Epoch 21060/999 | Loss 0.0001 | Win count 8529


[-0.54809999 -0.60148597 -0.9328478 ]
Epoch 21080/999 | Loss 0.0000 | Win count 8540


[-0.09279151  0.05815984 -0.18702006]
Epoch 21100/999 | Loss 0.0000 | Win count 8549


[ 0.19135268 -0.47800899 -0.19233252]
Epoch 21120/999 | Loss 0.0003 | Win count 8558


[-0.17057025 -0.30761486 -0.44618538]
Epoch 21140/999 | Loss 0.0000 | Win count 8567


[-0.3528915  -0.49913576 -0.7935586 ]
Epoch 21160/999 | Loss 0.0001 | Win count 8578


[-0.50080228 -0.32936591 -0.11031382]
Epoch 21180/999 | Loss 0.0006 | Win count 8581


[ 0.77253348 -0.18902206 -0.15159553]
Epoch 21200/999 | Loss 0.0006 | Win count 8588


[-0.12839216 -0.46564454 -0.2269204 ]
Epoch

[ 0.1801998  -0.18891019 -0.43796253]
Epoch 22900/999 | Loss 0.0000 | Win count 9243


[-0.25760856 -0.51647723 -0.55053151]
Epoch 22920/999 | Loss 0.0000 | Win count 9254


[ 0.16355509 -0.81627846 -0.47501794]
Epoch 22940/999 | Loss 0.0001 | Win count 9259


[-0.07383451 -0.38792419 -0.38148871]
Epoch 22960/999 | Loss 0.0002 | Win count 9266


[ 0.16078907 -0.82411641 -0.48415652]
Epoch 22980/999 | Loss 0.0000 | Win count 9271


[ 0.07060829 -0.50130737 -0.3689785 ]
Epoch 23000/999 | Loss 0.0010 | Win count 9281


[-0.45336449 -0.09148511 -0.69161636]
Epoch 23020/999 | Loss 0.0001 | Win count 9288


[ 0.17965931 -0.24304056 -0.08357134]
Epoch 23040/999 | Loss 0.0001 | Win count 9295


[-0.03575192 -0.18698275 -0.3045319 ]
Epoch 23060/999 | Loss 0.0000 | Win count 9302


[-0.03161576 -0.19408458 -0.30206156]
Epoch 23080/999 | Loss 0.0000 | Win count 9315


[-0.7350533  -0.44770432 -0.38885641]
Epoch 23100/999 | Loss 0.0000 | Win count 9322


[-0.14366785 -0.18145552 -0.30356473]
Epoch

[-0.09014363 -0.44420612 -0.28528067]
Epoch 24800/999 | Loss 0.0000 | Win count 9974


[ 0.02313654 -0.62631524 -0.35590085]
Epoch 24820/999 | Loss 0.0000 | Win count 9979


[-0.18136123 -0.25650543 -0.57329792]
Epoch 24840/999 | Loss 0.0002 | Win count 9986


[-0.05041535 -0.23017189 -0.30155596]
Epoch 24860/999 | Loss 0.0000 | Win count 9992


[ 0.1723648  -0.34936702 -0.1384287 ]
Epoch 24880/999 | Loss 0.0000 | Win count 10001


[-0.74169779 -0.50644958 -0.37005866]
Epoch 24900/999 | Loss 0.0000 | Win count 10004


[-0.59854782 -0.4662528  -0.45869261]
Epoch 24920/999 | Loss 0.0001 | Win count 10015


[-0.04978273 -0.22609922 -0.30466425]
Epoch 24940/999 | Loss 0.0000 | Win count 10023


[ 0.22562556 -0.34887099 -0.36259767]
Epoch 24960/999 | Loss 0.0001 | Win count 10029


[-0.34429044 -0.34715194 -0.77337372]
Epoch 24980/999 | Loss 0.0000 | Win count 10038


[-0.12574956  0.13002869 -0.27856877]
Epoch 25000/999 | Loss 0.0000 | Win count 10042


[-0.11775971 -0.44768184 -0.28573319

[ 0.14444461 -0.27262297 -0.42949361]
Epoch 26680/999 | Loss 0.0000 | Win count 10721


[ 0.80567509 -0.30238321  0.17321374]
Epoch 26700/999 | Loss 0.0001 | Win count 10730


[ 0.16400465 -0.36876348 -0.17347804]
Epoch 26720/999 | Loss 0.0001 | Win count 10738


[-0.50671172 -0.23182809 -0.30744985]
Epoch 26740/999 | Loss 0.0000 | Win count 10748


[ 0.13336158 -0.08763202 -0.52587593]
Epoch 26760/999 | Loss 0.0000 | Win count 10757


[-0.28928721 -0.14578931 -0.55648565]
Epoch 26780/999 | Loss 0.0001 | Win count 10765


[-0.30056503 -0.14908126 -0.55599844]
Epoch 26800/999 | Loss 0.0000 | Win count 10777


[-0.06306773 -0.23264781 -0.30577034]
Epoch 26820/999 | Loss 0.0000 | Win count 10785


[-0.08033223 -0.24367276 -0.30590147]
Epoch 26840/999 | Loss 0.0000 | Win count 10792


[-0.07567851 -0.23943728 -0.3060292 ]
Epoch 26860/999 | Loss 0.0000 | Win count 10799


[-0.15047723 -0.17501225 -0.53975731]
Epoch 26880/999 | Loss 0.0000 | Win count 10809


[-0.29675436 -0.3871628  -1.0541

[-0.32042122 -0.95451081 -0.71050262]
Epoch 28560/999 | Loss 0.0000 | Win count 11490


[-0.26582694 -0.65802717 -0.14955978]
Epoch 28580/999 | Loss 0.0009 | Win count 11498


[ 0.14679901 -0.07001796 -0.54711401]
Epoch 28600/999 | Loss 0.0002 | Win count 11506


[-0.06919812 -0.23292482 -0.28840387]
Epoch 28620/999 | Loss 0.0000 | Win count 11515


[-0.06595691 -0.2277211  -0.29009363]
Epoch 28640/999 | Loss 0.0000 | Win count 11531


[-0.32334229 -0.32011521 -0.13269736]
Epoch 28660/999 | Loss 0.0000 | Win count 11541


[-0.38946381 -0.16120493 -0.73883426]
Epoch 28680/999 | Loss 0.0000 | Win count 11551


[-0.32136151 -0.31148699 -0.1297313 ]
Epoch 28700/999 | Loss 0.0000 | Win count 11559


[ 0.14083961 -0.24378316 -0.41987026]
Epoch 28720/999 | Loss 0.0000 | Win count 11570


[-0.13693808 -0.13907278 -0.58955538]
Epoch 28740/999 | Loss 0.0000 | Win count 11578


[-0.12782338 -0.32921845 -0.22003429]
Epoch 28760/999 | Loss 0.0000 | Win count 11583


[-0.72759491 -0.40500444 -0.3670

[ 0.15416087 -0.70655096 -0.41719422]
Epoch 30440/999 | Loss 0.0000 | Win count 12306


[-0.06025504 -0.24075529 -0.29628024]
Epoch 30460/999 | Loss 0.0000 | Win count 12316


[-0.38730556 -0.61907595 -0.87977779]
Epoch 30480/999 | Loss 0.0000 | Win count 12319


[ 0.12102074 -0.35481682 -0.16433038]
Epoch 30500/999 | Loss 0.0000 | Win count 12327


[-0.17171696 -0.22554776 -0.56972843]
Epoch 30520/999 | Loss 0.0000 | Win count 12335


[ 0.22952586 -0.21250284 -0.43238199]
Epoch 30540/999 | Loss 0.0000 | Win count 12344


[-0.05805973 -0.24023251 -0.29643443]
Epoch 30560/999 | Loss 0.0000 | Win count 12349


[ 0.11904167 -0.35640484 -0.16891634]
Epoch 30580/999 | Loss 0.0000 | Win count 12358


[-0.44699812 -0.34471267 -0.11484551]
Epoch 30600/999 | Loss 0.0000 | Win count 12365


[-0.29308364 -0.23951481 -0.53071874]
Epoch 30620/999 | Loss 0.0000 | Win count 12375


[-0.05426445 -0.24055718 -0.29289326]
Epoch 30640/999 | Loss 0.0000 | Win count 12385


[-0.28302822 -0.22334659 -0.5235

[-0.19712725 -0.20357418 -0.46392995]
Epoch 32320/999 | Loss 0.0000 | Win count 13121


[-0.19712752 -0.20266542 -0.46256801]
Epoch 32340/999 | Loss 0.0000 | Win count 13133


[ 0.20878647 -0.13036011 -0.2044237 ]
Epoch 32360/999 | Loss 0.0000 | Win count 13140


[-0.19333498 -0.18679142 -0.45946822]
Epoch 32380/999 | Loss 0.0000 | Win count 13149


[-0.20217404 -0.20152536 -0.46723408]
Epoch 32400/999 | Loss 0.0001 | Win count 13160


[ 0.21587744 -0.12511706 -0.19335164]
Epoch 32420/999 | Loss 0.0000 | Win count 13166


[ 0.10668539 -1.02908349 -0.92904234]
Epoch 32440/999 | Loss 0.0000 | Win count 13175


[-0.03035419 -0.6810779  -0.23509787]
Epoch 32460/999 | Loss 0.0000 | Win count 13180


[-0.19459046 -0.1933618  -0.46343493]
Epoch 32480/999 | Loss 0.0000 | Win count 13188


[-0.66386825 -0.67983103 -0.8173458 ]
Epoch 32500/999 | Loss 0.0001 | Win count 13197


[-0.19491951 -0.19987538 -0.46562359]
Epoch 32520/999 | Loss 0.0000 | Win count 13203


[-0.02636668 -0.68696702 -0.2378

[ 0.18073454 -0.23368941 -0.39991313]
Epoch 34200/999 | Loss 0.0000 | Win count 13960


[-0.81402862 -0.39472064 -0.34161964]
Epoch 34220/999 | Loss 0.0000 | Win count 13965


[-0.29039326 -0.24352549 -0.11472288]
Epoch 34240/999 | Loss 0.0000 | Win count 13974


[-0.22592157 -0.27717212 -0.52802509]
Epoch 34260/999 | Loss 0.0000 | Win count 13985


[ 0.14318982 -0.35209319 -0.09962327]
Epoch 34280/999 | Loss 0.0000 | Win count 13994


[-0.47277096 -0.24591798 -0.67357284]
Epoch 34300/999 | Loss 0.0000 | Win count 14002


[-0.81520921 -0.39714357 -0.3432118 ]
Epoch 34320/999 | Loss 0.0000 | Win count 14007


[ 0.10943341  0.00991804 -0.38780394]
Epoch 34340/999 | Loss 0.0000 | Win count 14012


[-0.22392131 -0.2137416  -0.4426119 ]
Epoch 34360/999 | Loss 0.0000 | Win count 14021


[-0.46344873 -0.40866509 -0.07780586]
Epoch 34380/999 | Loss 0.0000 | Win count 14028


[ 0.11967693  0.01031689 -0.38762948]
Epoch 34400/999 | Loss 0.0000 | Win count 14039


[-0.18545863  0.13925248 -0.3051

[-0.22468832 -0.30033907 -0.57237113]
Epoch 36080/999 | Loss 0.0000 | Win count 14688


[ 0.2469575  -0.5735321  -0.31517383]
Epoch 36100/999 | Loss 0.0000 | Win count 14696


[-0.76637703 -0.41286194 -0.32919848]
Epoch 36120/999 | Loss 0.0000 | Win count 14703


[-0.38753611 -0.36170244 -0.71714956]
Epoch 36140/999 | Loss 0.0000 | Win count 14712


[-0.20651898 -0.12981907  0.07366604]
Epoch 36160/999 | Loss 0.0000 | Win count 14719


[-0.43372554 -0.21412978 -0.63477421]
Epoch 36180/999 | Loss 0.0000 | Win count 14725


[-0.03757237 -0.21633364 -0.30498749]
Epoch 36200/999 | Loss 0.0007 | Win count 14738


[-0.37864405 -0.57401973 -1.10069954]
Epoch 36220/999 | Loss 0.0000 | Win count 14744


[ 0.15673855 -0.60572231 -0.40449655]
Epoch 36240/999 | Loss 0.0000 | Win count 14750


[ 0.14622918  0.00193388 -0.4745453 ]
Epoch 36260/999 | Loss 0.0001 | Win count 14760


[-0.05906117 -0.22710112 -0.30713096]
Epoch 36280/999 | Loss 0.0000 | Win count 14768


[-0.33687204 -0.25924024 -0.4702

[-0.3713432  -0.55146527 -1.17871118]
Epoch 37960/999 | Loss 0.0001 | Win count 15427


[-0.2062797  -0.10714871  0.08898275]
Epoch 37980/999 | Loss 0.0000 | Win count 15438


[ 0.69630605 -0.42198655  0.17764986]
Epoch 38000/999 | Loss 0.0000 | Win count 15447


[ 0.04195515 -0.47695011 -0.22701003]
Epoch 38020/999 | Loss 0.0000 | Win count 15455


[-0.06414905 -0.30433637 -0.3405399 ]
Epoch 38040/999 | Loss 0.0000 | Win count 15464


[-0.3656413  -0.54693371 -1.17959881]
Epoch 38060/999 | Loss 0.0000 | Win count 15472


[-0.22779602 -0.3126151  -0.55647641]
Epoch 38080/999 | Loss 0.0000 | Win count 15480


[ 0.21073347 -0.22251794 -0.42352447]
Epoch 38100/999 | Loss 0.0000 | Win count 15489


[ 0.1659961  -0.18793032 -0.26487538]
Epoch 38120/999 | Loss 0.0000 | Win count 15494


[-0.20417047 -0.4584716  -0.37174368]
Epoch 38140/999 | Loss 0.0000 | Win count 15502


[-0.39632693 -0.91027606 -0.17618863]
Epoch 38160/999 | Loss 0.0000 | Win count 15512


[-0.04666312 -0.21534185 -0.3025

[-0.75475854 -0.40039885 -0.32489884]
Epoch 39840/999 | Loss 0.0000 | Win count 16257


[ 0.12298153 -0.37462136 -0.06023546]
Epoch 39860/999 | Loss 0.0000 | Win count 16266


[-0.18067767 -0.42008656 -0.40658206]
Epoch 39880/999 | Loss 0.0000 | Win count 16275


[ 0.20746934 -0.20182121 -0.39907467]
Epoch 39900/999 | Loss 0.0000 | Win count 16285


[-0.21831942 -0.2941713  -0.55625302]
Epoch 39920/999 | Loss 0.0000 | Win count 16295


[-0.35732779 -0.43336004 -1.13049901]
Epoch 39940/999 | Loss 0.0000 | Win count 16303


[ 0.03602281 -0.68385661 -0.8420881 ]
Epoch 39960/999 | Loss 0.0000 | Win count 16312


[-0.23958421 -0.24895565 -0.11846675]
Epoch 39980/999 | Loss 0.0000 | Win count 16326


[-0.75980181 -0.40094742 -0.32335305]
Epoch 40000/999 | Loss 0.0002 | Win count 16334


[-0.23960583 -0.13366038  0.07194759]
Epoch 40020/999 | Loss 0.0000 | Win count 16341


[-0.34662929 -0.4376888  -1.13587856]
Epoch 40040/999 | Loss 0.0000 | Win count 16345


[-0.337345   -0.36497819  0.0168

[-0.19711955 -0.56241179 -0.19400778]
Epoch 41720/999 | Loss 0.0000 | Win count 17097


[ 0.15151174 -1.02629495 -0.86609888]
Epoch 41740/999 | Loss 0.0000 | Win count 17106


[-0.37808681 -0.15299843 -0.64312619]
Epoch 41760/999 | Loss 0.0000 | Win count 17111


[-0.29621562 -0.26843911 -0.42821309]
Epoch 41780/999 | Loss 0.0000 | Win count 17119


[-0.41408354 -0.90361011 -0.12120152]
Epoch 41800/999 | Loss 0.0000 | Win count 17127


[-0.36774054 -0.35814524  0.02476309]
Epoch 41820/999 | Loss 0.0000 | Win count 17136


[-0.79959023 -0.38048178 -0.56073582]
Epoch 41840/999 | Loss 0.0000 | Win count 17144


[ 0.29470327 -0.16207451  0.02719171]
Epoch 41860/999 | Loss 0.0000 | Win count 17154


[-0.2015273  -0.55446148 -0.19505155]
Epoch 41880/999 | Loss 0.0000 | Win count 17161


[-0.21654037 -0.2995691  -0.5605011 ]
Epoch 41900/999 | Loss 0.0000 | Win count 17171


[ 0.78047436 -0.15455505 -0.24498467]
Epoch 41920/999 | Loss 0.0000 | Win count 17177


[ 0.12205113 -0.37279043 -0.0677

[ 0.12473498 -0.32253939 -0.08796746]
Epoch 43600/999 | Loss 0.0000 | Win count 17898


[ 0.12369414 -0.32286012 -0.08883239]
Epoch 43620/999 | Loss 0.0000 | Win count 17906


[-0.11106365 -0.35295749 -0.27015138]
Epoch 43640/999 | Loss 0.0000 | Win count 17913


[-0.04833394 -0.18622109 -0.29844549]
Epoch 43660/999 | Loss 0.0000 | Win count 17920


[ 0.30122933 -0.29394984 -0.56370103]
Epoch 43680/999 | Loss 0.0000 | Win count 17927


[-0.76568425 -0.44938388 -0.37418941]
Epoch 43700/999 | Loss 0.0000 | Win count 17932


[-0.22319534 -0.33877185 -0.55431843]
Epoch 43720/999 | Loss 0.0000 | Win count 17942


[ 0.39885762 -0.17847773 -0.03947336]
Epoch 43740/999 | Loss 0.0000 | Win count 17948


[-0.33281007 -0.35670972 -0.43748209]
Epoch 43760/999 | Loss 0.0000 | Win count 17957


[-0.09949536 -0.39311227 -0.30743679]
Epoch 43780/999 | Loss 0.0000 | Win count 17966


[ 0.20673761 -0.20294517 -0.40863672]
Epoch 43800/999 | Loss 0.0000 | Win count 17973


[-0.36098886 -0.167404   -0.6545

[-0.39958262 -0.89447916 -0.14062694]
Epoch 45480/999 | Loss 0.0001 | Win count 18711


[-0.40840062 -0.89888674 -0.1399143 ]
Epoch 45500/999 | Loss 0.0000 | Win count 18720


[-0.40983999 -0.90909266 -0.14276457]
Epoch 45520/999 | Loss 0.0000 | Win count 18728


[-0.04784976 -0.16902345 -0.30195469]
Epoch 45540/999 | Loss 0.0000 | Win count 18736


[-0.06708381 -0.31766319 -0.2525039 ]
Epoch 45560/999 | Loss 0.0000 | Win count 18748


[-0.20259501 -0.3707526  -0.58240432]
Epoch 45580/999 | Loss 0.0000 | Win count 18759


[-0.2797583  -0.59231758 -1.11340928]
Epoch 45600/999 | Loss 0.0000 | Win count 18767


[-0.30377683 -0.1311536   0.03415487]
Epoch 45620/999 | Loss 0.0000 | Win count 18777


[ 0.015526   -0.34392288 -0.42287084]
Epoch 45640/999 | Loss 0.0001 | Win count 18786


[ 0.33042514 -0.3011193  -0.00149043]
Epoch 45660/999 | Loss 0.0000 | Win count 18794


[ 0.21817416 -0.21973726 -0.41741839]
Epoch 45680/999 | Loss 0.0000 | Win count 18801


[-0.20117979 -0.36760554 -0.5803

[-0.19366282 -0.28006613 -0.61438262]
Epoch 47360/999 | Loss 0.0000 | Win count 19573


[ 0.79440033 -0.12757021 -0.38022095]
Epoch 47380/999 | Loss 0.0000 | Win count 19582


[-0.1113753  -0.42679247 -0.41324455]
Epoch 47400/999 | Loss 0.0000 | Win count 19593


[-0.37331152 -0.51699525 -0.06074867]
Epoch 47420/999 | Loss 0.0000 | Win count 19597


[-0.00345539 -0.33915713 -0.42635998]
Epoch 47440/999 | Loss 0.0000 | Win count 19607


[-0.11074962 -0.41177428 -0.40934017]
Epoch 47460/999 | Loss 0.0000 | Win count 19617


[-0.28369117 -0.52881789 -1.21184146]
Epoch 47480/999 | Loss 0.0000 | Win count 19628


[-0.5171206  -0.68880481 -0.71699739]
Epoch 47500/999 | Loss 0.0000 | Win count 19637


[-0.28438962 -0.24636312 -0.14191383]
Epoch 47520/999 | Loss 0.0000 | Win count 19644


[-0.37937319 -0.81567425 -0.64769411]
Epoch 47540/999 | Loss 0.0000 | Win count 19651


[-0.37323812 -0.23717389  0.09185698]
Epoch 47560/999 | Loss 0.0000 | Win count 19660


[ 0.2155174  -0.22852236 -0.4076

[ 0.0078352  -0.34142157 -0.42455658]
Epoch 49240/999 | Loss 0.0000 | Win count 20387


[-0.05104415 -0.18567502 -0.30658677]
Epoch 49260/999 | Loss 0.0000 | Win count 20397


[-0.03582812 -0.31492889 -0.23688312]
Epoch 49280/999 | Loss 0.0000 | Win count 20405


[-0.27212963 -0.11925817  0.06586813]
Epoch 49300/999 | Loss 0.0000 | Win count 20415


[-0.31770885 -0.34411886 -0.73625422]
Epoch 49320/999 | Loss 0.0000 | Win count 20419


[-0.18287355 -0.23271096 -0.56799078]
Epoch 49340/999 | Loss 0.0000 | Win count 20426


[-0.18214443 -0.24253559 -0.57115948]
Epoch 49360/999 | Loss 0.0000 | Win count 20433


[ 0.08773279 -0.26165444 -0.05505484]
Epoch 49380/999 | Loss 0.0000 | Win count 20439


[-0.17962582 -0.2427592  -0.56748229]
Epoch 49400/999 | Loss 0.0000 | Win count 20449


[ 0.29378247 -0.20895261 -0.19998908]
Epoch 49420/999 | Loss 0.0000 | Win count 20455


[-0.1650613  -0.50013661 -0.2324394 ]
Epoch 49440/999 | Loss 0.0000 | Win count 20463


[ 0.20451325 -0.22823629 -0.3934

In [6]:
env = catcher()
policy.act([env.reset()])[0]

array([ 615.98175049,  636.49072266,  616.65515137], dtype=float32)

In [13]:
loss

1.2342154320776899e-07

NameError: name 'inputs' is not defined

In [ ]:
_,W1 = sess.run([updateModel,W],feed_dict={inputs1:inputs,nextQ:targets})