In [20]:
import tf_util  as U
from policies import Policy, CatchPolicy
from policies import catcher as catcher_off_pol
import pickle
from matplotlib import pyplot as plt
from es import make_session
import numpy as np
from policies import GRID_SIZE
     
            
class catcher():
    def __init__(self):
        self.observation_space = np.zeros((GRID_SIZE, GRID_SIZE)).ravel()
        self.action_space = np.array([2])

    def step(self, ac):
        return self.ep.send(ac)

    def reset(self):
        self.ep = episode()
        S, won, _, _ = self.ep.__next__()
        return S
    
    
def episode():
    """
    Coroutine of episode.

    Action has to be explicitly send to this coroutine.
    """
    x, y, z = (
        np.random.randint(0, GRID_SIZE),  # X of fruit
        0,  # Y of dot
        np.random.randint(1, GRID_SIZE - 1)  # X of basket
    )
    while True:
        X = np.zeros((GRID_SIZE, GRID_SIZE))  # Reset grid
        X[y, x] = 1.  # Draw fruit
        bar = range(z - 1, z + 2)
        X[-1, bar] = 1.  # Draw basket

        # End of game is known when fruit is at penultimate line of grid.
        # End represents either a win or a loss
        end = int(y >= GRID_SIZE - 2)
        rew = end
        if end and x not in bar:
            rew *= -10
        
        print(X)
        action = yield X.ravel(), rew, end, None
        
        #assert action in [0, 1, 2]
        if end:
            break

        z = np.min([np.max([z + int(action[0]) - 1, 1]), GRID_SIZE - 2])
        y += 1



In [21]:
env = catcher()
sess = make_session(single_threaded=True)

def save_img():
    if 'images' not in os.listdir('.'):
        os.mkdir('images')
    frame = 0
    while True:
        screen = (yield)
        plt.imshow(screen[0], interpolation='none')
        plt.savefig('images/%03i.png' % frame)
        frame += 1
    
img_saver = save_img()
img_saver.next()

for _ in xrange(8):
    g = episode()
    S, _ = g.next()
    img_saver.send(S)
    try:
        while True:
            act = np.argmax(model.predict(S[np.newaxis]), axis=-1)[0] - 1
            S, _ = g.send(act)
            img_saver.send(S)

    except StopIteration:
        pass

img_saver.close()

In [22]:
cp = CatchPolicy(env.observation_space ,env.action_space, 'tanh', [100, 100], 'ff')
U.initialize()

TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

In [ ]:
1

In [7]:
cp.initialize_from('/tmp/es_master_31842/snapshot_iter00900_rew1.h5')

In [11]:
initialize

NameError: name 'initialize' is not defined

In [9]:
cp.rollout(env)



[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.

(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.], dtype=float32), 8)

# Generate experience

In [60]:
type(cp)

__main__.CatchPolicy

In [53]:

memory = []
for i in range(10000):
    episodList = []
    Xprev = env.reset()
    end = False
    
    while not end:
        
        action = np.random.randint(3)
        X, rew, end, _ = env.step([action])
        
        episodList.append((Xprev, action, rew))
        Xprev = X
        
        #if end:
        #    print(rew)
    memory.append(episodList)
    
pickle.dump(memory,open('memoryList.pickle', 'wb'))

TypeError: Required argument 'file' (pos 2) not found

In [ ]:
ob, rew, done, _ = env.step(ac)
ob = env.reset()

In [9]:
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])